#!/bin/bash 
find "$1" -name '*.flac'  -exec ffmpeg -y -i {} -ab 320k -map_metadata 0 -id3v2_version 3 {}.mp3 \;
find "$1" -name '*.flac' -print0 | while IFS= read -r -d $'\0' line; do
    mv "$line.mp3" "${line/flac/mp3}" && rm "$line"
done

find "$1" -name '*.m4a'  -exec ffmpeg -y -i {} -ab 320k -map_metadata 0 -id3v2_version 3 {}.mp3 \;
find "$1" -name '*.m4a' -print0 | while IFS= read -r -d $'\0' line; do
    mv "$line.mp3" "${line/m4a/mp3}" && rm "$line"
done



